# -----------------------------------------------------------------------------
# Global Config
# -----------------------------------------------------------------------------
set-option -g prefix M-`
unbind C-b
bind M-` send-prefix

set-option -g escape-time 0
set-option -g focus-events on
set-option -g mouse on
set-window-option -g mode-keys vi

# -----------------------------------------------------------------------------
# Display & Color (Optimized for WSL2 + Neovim)
# -----------------------------------------------------------------------------
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g status-style bg=default

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# -----------------------------------------------------------------------------
# Navigation & Layout (Vim-style for Compiler Dev)
# -----------------------------------------------------------------------------
# split-window - vertical | horizontal
bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

# Alt+hjkl to switch between panes instead of prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# -----------------------------------------------------------------------------
# Clipboard & Shell
# -----------------------------------------------------------------------------
set -s set-clipboard external
set -g history-limit 50000

bind-key v capture-pane -S - -b "temp-buffer" \; \
           save-buffer -b "temp-buffer" /tmp/tmux_capture.txt \; \
           delete-buffer -b "temp-buffer" \; \
           split-window -h "nvim /tmp/tmux_capture.txt -c 'normal G' && rm /tmp/tmux_capture.txt"

# -----------------------------------------------------------------------------
# Plugins (TPM)
# -----------------------------------------------------------------------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# continuum & resurrect config
set -g @continuum-save-interval '15'
#set -g @continuum-restore 'on'  # auto restore when reopen
set -g @resurrect-capture-pane-contents 'on'

# Catppuccin run & config
set -g @catppuccin_flavor "latte" # frappe/mocha
set -g @catppuccin_window_status_style "rounded"
run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_battery}"

run '~/.tmux/plugins/tpm/tpm'

