- name: deepseek/deepseek-v4-pro
  edit_format: diff
  use_repo_map: true
  caches_by_default: true
  use_temperature: false
  examples_as_sys_msg: false
  accepts_settings:
    - reasoning_effort

- name: deepseek/deepseek-v4-flash
  edit_format: diff
  use_repo_map: true
  caches_by_default: true
  examples_as_sys_msg: false

